env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_LOG_TIMESTAMP: true
task:
    name: aosp
    timeout_in: 120m
    container:
      image: apon77/aosp:cirrus
      cpu: 1
      memory: 4G
    build_script:
      - sleep 2
      - set -exv

      - rom_name=ppui

      - same_rom=2
      - if [[ same_rom -gt 1 ]]; then echo exit 1; fi

task:
    name: aosp2
    timeout_in: 120m
    depends_on:
      - aosp
    container:
      image: apon77/aosp:cirrus
      cpu: 1
      memory: 4G
    build_script:
      - sleep 2
