env:
    CIRRUS_CLONE_DEPTH: 1
    rclone_config: "ENCRYPTED[19d5b9ddf70db34d5e7e7d1ba44ca504ac80d3dce2fe64528cc1b4c163878b8af3a5b5cde016ac6716cf8db02118266f]"

task:
    name: aosp
    timeout_in: 120m
    container:
      image: apon77/aosp:cirrus
      cpu: 2
      memory: 4G
    build_script:
      - mkdir -p /home/cirrus/.config/rclone
      - echo ${rclone_config} > /home/cirrus/.config/rclone/rclone.conf
      - rclone listremotes
      - env
      - tmate -S /tmp/tmate.sock new-session -d
      - tmate -S /tmp/tmate.sock wait tmate-ready
      - tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'  
      - sleep 1h
