env:
    CIRRUS_CLONE_DEPTH: 1
    HOSTNAME: ci

task:
    name: aosp
    container:
        dockerfile: Dockerfile
        docker_arguments:
            userid: 1000
            groupid: 1000
            username: ci
            hostname: ci
        cpu: 2
        memory: 768M
#    rom_cache:
 #       folder: rom
  #      reupload_on_changes: false # since there is a fingerprint script
   #     fingerprint_script:
    #        - echo $resync
    #    populate_script: 
     #     - source src
    src_script: source src
    t_script: source t
