env:
    CIRRUS_CLONE_DEPTH: 1

task:
    name: source t
    env:
        resync: 1
    container:
        dockerfile: Dockerfile
        docker_arguments:
            userid: 1000
            groupid: 1000
            username: ci
        cpu: 1
        memory: 768M
    src_cache:
        folder: rom
        reupload_on_changes: true # since there is a fingerprint script
        fingerprint_script:
            - echo $resync
        populate_script: 
          - source t
    t_script: source t
