env:
    CIRRUS_CLONE_DEPTH: 1
task:
    name: aosp
    timeout_in: 120m
    container:
      image: apon77/aosp:cirrus
      cpu: 1
      memory: 2G
    build_script:
      - sleep 2
      - sudo whoami
    always:
      test_reports_script: echo pro
task:
    name: aosp2
    timeout_in: 120m
    depends_on:
      - aosp
    container:
      image: apon77/aosp:cirrus
      cpu: 1
      memory: 2G
    build_script:
      - sleep 2
