env:
    CIRRUS_CLONE_DEPTH: 1
    bot: "ENCRYPTED[c88d59fc34c60d888dad06231819d494c5f260fb746eb2a32c13b5b17d1cbf99b9974b8c2adc0b2fa46d433483b8ca58]"
task:
  name: aosp1
  timeout_in: 120m
  container:
    dockerfile: Dockerfile
    cpu: 1
    memory: 4G
  good_script:
      - echo $bot
      - echo 'whomai fine working thank you' > hello.tx
      - env
      - set
      - whoami
      - b2="ENCRYPTED[c88d59fc34c60d888dad06231819d494c5f260fb746eb2a32c13b5b17d1cbf99b9974b8c2adc0b2fa46d433483b8ca58]"
      - echo $"ENCRYPTED[c88d59fc34c60d888dad06231819d494c5f260fb746eb2a32c13b5b17d1cbf99b9974b8c2adc0b2fa46d433483b8ca58]"
      - echo $b2
      - rn='hello-r'
      - echo "rn=$rn" >> $CIRRUS_ENV
      - env
  exit_script:
      - env
      - echo hello i am exiting
      - exit 0
      - echo i am after exiting 0
  check_run_script:
      - echo am i running?
