env:
    CIRRUS_CLONE_DEPTH: 1
task:
    name: source t
    container:
        #image: Dockerfile
        dockerfile: Dockerfile
        docker_arguments:
            userid: 1000
            groupid: 1000
            username: ci
        cpu: 1
        memory: 768M
    t_script: source t
    who_script: whoami
