env:
    CIRRUS_CLONE_DEPTH: 1
    HOSTNAME: "ci"
    CCACHE_DIR: "/tmp/rom"
    USE_CCACHE: 1
    CCACHE_EXEC: "/usr/bin/ccache"
    CIRRUS_WORKING_DIR: "/tmp/apon"
    CI_NODE_TOTAL: 1

task:
    name: aosp
    timeout_in: 120m
    container:
        dockerfile: Dockerfile
        docker_arguments:
            userid: 1000
            groupid: 1000
            username: ci
        cpu: 8 #12cpu,14G ram got 1h schedule in concurrent build!
        memory: 16G #2cpu,14G ram may be optimum

    monitor_background_script:
        - ./background
    sync_script:
        - ./sync
    rom_cache:
       folder: /tmp/rom
         #build_script:
         #- ./build
    1aex_script:
      - source common
        #- make api-stubs-docs 
      - make bootimage -j24
    2aex_script:
      - source common
      - make system-api-stubs-docs -j 24
    3aex_script:
      - source common
      - make test-api-stubs-docs -j 24

    4aex_script:
      - source common
      - make app_process -j 24

    5aex_script:
      - source common
      - make init -j 24

    6aex_script:
      - source common
      - make app_process -j 24

    7aex_script:
      - source common
      - make framework -j 24

    8aex_script:
      - source common
      - make libbinder -j 24

    9aex_script:
      - source common
      - make services -j 24

    10aex_script:
      - source common
        #- make aex -j 24
