env:
    CIRRUS_CLONE_DEPTH: 1

task:
    name: source t
    container:
        dockerfile: Dockerfile
        docker_arguments:
            userid: 1000
            groupid: 1000
            username: ci
        cpu: 1
        memory: 768M
    shared_cache:
        folder: rom
        #reupload_on_changes: false # since there is a fingerprint script
        populate_script: 
          - mkdir hi
          - echo i am fine >> hi/ok.txt
    t_script: source t
