env:
    CIRRUS_CLONE_DEPTH: 1
    HOSTNAME: ci
    CCACHE_DIR: "/tmp/rom"
    USE_CCACHE: 1
    CCACHE_EXEC: "/usr/bin/ccache"

task:
    name: aosp
    timeout_in: 120m
    container:
        dockerfile: Dockerfile
        docker_arguments:
            userid: 1000
            groupid: 1000
            username: ci
        cpu: 8
        memory: 14G
    sync_script:
        - repo init -q --no-repo-verify --depth=1 -u git://github.com/AospExtended/manifest.git -b 11.x -g default,-device,-mips,-darwin,-notdefault
        - git clone https://github.com/Apon77Lab/android_.repo_local_manifests.git --depth 1 -b aex .repo/local_manifests
        - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30

    rom_cache:
       folder: /tmp/rom

    build_script:
        - . build/envsetup.sh
        - lunch aosp_mido-user
        - ccache -M 10G
        - make init -j 16
            # cache, out, upload, concurrent
