env:
    CIRRUS_CLONE_DEPTH: 1
task:
  name: aosp1
  timeout_in: 120m
  container:
    dockerfile: Dockerfile
    cpu: 4
    memory: 16G
  good_script:
      - rom_name=LineageOS
      - branch_name=lineage17.1
      - for item in "LineageOS lineage-17.1" "LineageOS lineage-15.1" "LineageOS lineage-19.0" "ArrowOS arrow-12.0" "Project-Fluid fluid-12" "CipherOS twelve" "ProjectRadiant twelve" "Project-Awaken 12" "Octavi-OS 12" "Project-LegionOS 12" "ShapeShiftOS android_12" "lighthouse-os sailboat"
      - do
      - item1=$(echo $item | awk -F ' ' '{print $1}')
      - item2=$(echo $item | awk -F ' ' '{print $2}')
      - if [[ $rom_name == $item1 ]]; then if [[ $branch_name == $item2 ]]; then rom_name=$rom_name-$branch_name; fi ;fi
      - done
      - while :; do echo testing; sleep 2m; done
      - exit 1
    
    
task:
    name: aosp
    timeout_in: 120m
    container:
      image: ubuntu:latest
      cpu: 2
      memory: 4G
    always:
      test_reports_script: echo pro
    build_script:
      - sleep 2
      - exit 1
task:
    name: aosp2
    timeout_in: 120m
    depends_on:
      - aosp
    container:
      image: ubuntu:latest
      cpu: 2
      memory: 4G
    build_script:
      - sleep 2
