env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[645c8c31a5f0311cdadc4448b651191ee3f8ebea524e4d8078b443e25d1cc4ed8ae9001699841b0ded6b3a3d3327fd6b]"

task:
    name: aosp
    timeout_in: 120m
    container:
      image: apon77/aosp:latest
      cpu: 1 #12cpu,14G ram got 1h schedule in concurrent build!
      memory: 2G #2cpu,14G ram may be optimum
    download_ccache_background_script:
      - ./download_ccache
    swapfile_background_script:
      - ./swapfile
    sync_script:
      - ./sync
    monitor_background_script:
      - ./monitor
    build_script:
      - ./build
    upload_ccache_script:
      - ./upload_ccache
