env:
    CIRRUS_CLONE_DEPTH: 1
    HOSTNAME: ci
    CCACHE_DIR: "/tmp/rom"
    USE_CCACHE: 1
    CCACHE_EXEC: "/usr/bin/ccache"

task:
    name: aosp
    timeout_in: 120m
    container:
        dockerfile: Dockerfile
        docker_arguments:
            userid: 1000
            groupid: 1000
            username: ci
        cpu: 8 #12cpu,14G ram got 1h schedule in concurrent build!
        memory: 12G #8cpu,14G ram may be optimum

    monitor_background_script:
        - ./background
    sync_script:
        - ./sync
    rom_cache:
       folder: /tmp/rom
         #build_script:
         #- ./build
    part1_script:
      - source common
      - mmm frameworks



task:
    name: aosp
    timeout_in: 120m
    container:
        dockerfile: Dockerfile
        docker_arguments:
            userid: 1000
            groupid: 1000
            username: ci
        cpu: 8 #12cpu,14G ram got 1h schedule in concurrent build!
        memory: 12G #8cpu,14G ram may be optimum

    monitor_background_script:
        - ./background
    sync_script:
        - ./sync
    rom_cache:
       folder: /tmp/rom
         #build_script:
         #- ./build
    part2_script:
      - source common
      - mmm external/dtc external/llvm external/toybox external/libcxx external/expat external/giflib
