env:
    CIRRUS_CLONE_DEPTH: 1
    HOSTNAME: ci
    var: "env ok"

task:
    name: aosp
    container:
        dockerfile: Dockerfile
        docker_arguments:
            userid: 1000
            groupid: 1000
            username: ci
        #cpu: 4
        #memory: 16G
        cpu: 1
        memory: 1G
    sync_script:
        - repo init -q --no-repo-verify --depth=1 -u git://github.com/AospExtended/manifest.git -b 11.x -g default,-device,-mips,-darwin,-notdefault
        - git clone https://github.com/Apon77Lab/android_.repo_local_manifests.git --depth 1 -b aex .repo/local_manifests
          #- repo sync -q -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 device/xiaomi/mido
          #- curl -Os https://roms.apon77.workers.dev/clang/prebuilts.tar.gz && tar xf prebuilts.tar.gz && rm prebuilts.tar.gz
    rom_cache:
       folder: /tmp/ok
       reupload_on_changes: false # since there is a fingerprint script
       fingerprint_script:
         - echo $resync
       populate_script: 
         - echo ok
    lunch_script:
        - ls -lah
        - pwd
          #- . build/envsetup.sh
          # - lunch aosp_mido-user
    build_script:
            # - make init
            # cache, out, upload, concurrent
