env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[645c8c31a5f0311cdadc4448b651191ee3f8ebea524e4d8078b443e25d1cc4ed8ae9001699841b0ded6b3a3d3327fd6b]"

task:
    name: aosp
    timeout_in: 120m
    container:
      image: apon77/aosp:cirrus
      cpu: 2
      memory: 4G
    build_script:
      - mkdir -p /home/cirrus/.config/rclone
      - echo $rclone_config > /home/cirrus/.config/rclone/rclone.conf
      - rclone listremotes
      - env
