task:
    name: source t
    container:
        #image: Dockerfile
        dockerfile: Dockerfile
        docker_arguments:
            userid: $(id -u)
            groupid: $(id -g)
            username: $(id -un)
        cpu: 1
        memory: 768M
    t_script: source t
