env:
    CIRRUS_CLONE_DEPTH: 1
task:
  name: aosp1
  timeout_in: 120m
  container:
    dockerfile: Dockerfile
    cpu: 4
    memory: 16G
  good_script:
      - sudo apt update
      - sudo apt install tmate -y
      - tmate -S /tmp/tmate.sock new-session -d
      - tmate -S /tmp/tmate.sock wait tmate-ready
      - send_shell=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
      - echo $send_shell
      - sleep 2h
      - exit 1
    
    
task:
    name: aosp
    timeout_in: 120m
    container:
      image: ubuntu:latest
      cpu: 2
      memory: 4G
    always:
      test_reports_script: echo pro
    build_script:
      - sleep 2
      - exit 1
task:
    name: aosp2
    timeout_in: 120m
    depends_on:
      - aosp
    container:
      image: ubuntu:latest
      cpu: 2
      memory: 4G
    build_script:
      - sleep 2
