env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[eed8f6b3ca25c588cd1973688775ea44c38162dc6f466e5511a5fe2f6b9efd96a5d6b6f8163b962f7bb3c2fbdc0fdbe4]"

task:
    name: aosp
    timeout_in: 120m
    container:
      image: apon77/aosp:latest
      cpu: 4 #12cpu,14G ram got 1h schedule in concurrent build!
      memory: 16G #2cpu,14G ram may be optimum
    download_ccache_background_script:
      - echo first time no ccache
    sync_script:
      - ./sync
    build_script:
      - ./build
    upload_ccache_script:
      - ./upload_ccache
