env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[645c8c31a5f0311cdadc4448b651191ee3f8ebea524e4d8078b443e25d1cc4ed8ae9001699841b0ded6b3a3d3327fd6b]"

task:
    name: aosp
    timeout_in: 120m
    container:
      image: apon77/aosp:ccache
      cpu: 8
      memory: 32G
    download_ccache_background_script:
      - ./download_ccache
    upload_ccache_bg_background_script:
      - echo ok
      # - ./upload_ccache_bg
    sync_script:
      - ./sync
    monitor_background_script:
      - ./monitor
    build_script:
      - ./build
    upload_ccache_script:
      echo ok
      #- ./upload_ccache
