kind: pipeline
name: aosp

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: all
  image: apon77/aosp:latest
  failure: ignore
  volumes:
    - name: vol
      path: /tmp
  commands:
    - timeout 45m ./all
- name: ccache
  image: apon77/aosp:latest
  environment:
    rclone_config:
      from_secret: rclone_config
  volumes:
    - name: vol
      path: /tmp
  commands:
    - echo ok
    - ./ccache

volumes:
  - name: vol
    temp: {}
