#!/bin/bash

cd /tmp/rom
. build/envsetup.sh
lunch aosp_mido-user
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z
make api-stubs-docs || echo sorry
make hiddenapi-lists-docs || echo sorry
make system-api-stubs-docs || echo sorry
make test-api-stubs-docs || echo sorry
make aex -j10|| deldog out/error.log
#sleep 100m
#kill $(pidof soong_ui)
#kill $(pidof make)
ccache -s
up(){
	curl --upload-file $1 https://transfer.sh/$(basename $1)
	echo
}

up out/target/product/mido/*.zip
