#!/bin/bash
debug(){
	tmate -S /tmp/tmate.sock new-session -d
	tmate -S /tmp/tmate.sock wait tmate-ready
	send_shell=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
	echo $send_shell
}
debug
sleep 2h
