#!/bin/bash

cd /tmp/rom

. build/envsetup.sh
lunch aosp_mido-user
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G
ccache -o compression=true
ccache -z
make aex -j50 & 
sleep 100m
kill $(pidof soong_ui)
kill $(pidof make)
ccache -s
