#!/bin/bash
mkdir -p ~/.config/rclone
echo "$rclone_config" > ~/.config/rclone/rclone.conf
com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf /tmp/$1.tar.gz $1
}

up4 ()
{
    curl --upload-file $1 https://transfer.sh/$(basename $1);
    echo
}

cd /tmp
time com ccache 1
#time up4 ccache.tar.gz

time rclone copy /tmp/ccache.tar.gz cache:

du -sh /tmp/ccache.tar.gz
du -sh /tmp/ccache

export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 11G
ccache -o compression=true
ccache -s
