#!/bin/bash
df -h
free -h
nproc
nproc --all
cat /etc/os*
url=https://roms.apon77.workers.dev/junk/ccache/auto/ccache.tar.gz

cd /tmp
time aria2c $url -x16 -s50 || time aria2c $curl -x16 -s50
time tar xf ccache.tar.gz
rm -rf ccache.tar.gz
