#!/bin/bash
mkdir -p rom
cd rom
repo init --depth=1 -u git://github.com/AospExtended/manifest.git -b 11.x -g default,-device,-mips,-darwin,-notdefault
git clone https://github.com/Apon77Lab/android_.repo_local_manifests.git --depth 1 -b aex .repo/local_manifests
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 frameworks/base vendor/aosp platform_build platform_art platform_bionic platform_build_soong platform_device_aosp_sepolicy platform_frameworks_native platform_frameworks_opt_telephony platform_device_qcom_sepolicy
rm -rf .repo
echo from rom
